name: Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
        default: testing
  push:
    branches:
      - main
      - dev
env:
  MONGO_DB_NAME: gha-demo
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
      FIRST: ${{ secrets.FIRST:0:4 }}
    environment: ${{ github.event_name == 'push' && 'testing' || inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Print environment name
        run: echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
      - name: Print environment variable
        run: echo "Secret is  ${{ env.FIRST }}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "..."
